Dev1
k-jinma/SpringPractice pull request #3
Opened 2024-09-01 12:51 UTC by Hinako-git

今回もよろしくお願いします。

2024-09-01 15:27 UTC, k-jinma requested changes
customer/list.html にページネーションのエリアがありますが、そのエリアで"${users}"が使用されていて、それが解決されないためにエラーが発生していました。
"${users...}"を"${customers...}に修正すると動作します。

2024-09-01 16:21 UTC, k-jinma requested changes
先ほど修正箇所のヒントをコメントしました。ご確認ください。

2024-09-04 13:34 UTC, Hinako-git commented
修正をプッシュしました。プルリクはしていません。
Gitの使い方について理解が不十分なため、間違っていたら教えてください！

2024-09-04 14:13 UTC, merged

2024-09-04 14:13 UTC, k-jinma commented
Issue1はこれでOKです。お疲れさまでした。
Issue2をまだ取り組んでいなければ、dev2ブランチを作って作業してみましょうか。不明ならdev1のままで構いません。

2024-09-05 03:45 UTC, Hinako-git commented
ありがとうございました。
ブランチを切るのは慣れてないのですが、やってみます。とりあえず次の授業までにissue2は進めます。

2024-09-05 03:50 UTC, k-jinma commented
そういえば、今回のIssue1の作業をmainに反映したいので、dev1ブランチをmainブランチにマージします。その後、mainブランチからdev2ブランチを作る手順になります。
あとで手順書を送ります。

2024-09-05 20:18 UTC, Hinako-git commented
マージしてからブランチを切るとのこと、承知しました。手順書を作ってくださるとのこと、ありがとうございます！

2024-09-06 02:18 UTC, k-jinma commented
@Hinako-git 
手順書を作りました。
環境や設定が異なっていたらこの手順書どおりにいかないかもしれません。
その場合は、dev1のままIssue2を続けてください。

[GitHubマージの方法.pdf](https://github.com/user-attachments/files/16902021/GitHub.pdf)

2024-09-06 09:46 UTC, Hinako-git commented
pdfを作ってくださり、ありがとうございます。
マージもissueも進めます！